export interface Disciplina {
    id: number,
    nome: string,
    versao: string,
    up: string,
    disciplinaAntiga: string;
    area: string,
    excluida: string,
    status: "Não Iniciada" | "Produzindo" | "Pronta para Oferta" | "Finalizada",
    ano: string,
    prioridade: "" | "Baixa" | "Normal" | "Alta",
    orientadores: Profissional[],
    statusMatriz: string,
    linkMatriz: string,
    desenho: string,
    ementa: string,
    isbn: string,
    padrao: string,
    detalhamento: string,
    ambiente: "100%" | "20%" | "Ambos",
    liberadoCriacao: boolean
    codAVA20: string,
    codAVA100: string,
    topicos: Topico[],
}
export interface Profissional {
    id: number,
    nome: string,
    email: string,
    telefone: string,
    foto: string,
    internoExterno: "Interno" | "Externo",
    treinamentos: string,
    admin: boolean,
    temAcesso: boolean,
}
export interface Video {
    id: string,
    idDisciplina: number,
    topicoNum: number,
    backup: boolean,
    tipo: "Apresentação" | "Videoaula" | "Video Embutido" | "Videocast",
    recursosEspeciaisVideo: string,
    gravacaoInternaExterna: "Interna" | "Externa",
    status: "Não Gravado" | "Liberado OC" | "Agendado" | "Gravado" | "Editado" | "Postado" | "Problema" | "Aguardando Agendamento",
    codigoVimeo: string,
    apresentador: Profissional[],
    convidado: Profissional[],
    dataLiberacao: Date | "",
    dataEmail: Date | "",
    dataAgendamento: Date | "",
    orcamento: string,
    versao: string,
    videoAutorizado: boolean,
    catProblema: string,
    descProblema: string,
    excluido: "" | "Excluído"
}
export interface Topico {
    id: string,
    idDisciplina: number,
    tipo: "Completo" | "Video"
    numero: number,
    conteudistas: Profissional[],
    validadores: Profissional[],
    status: "Nada" | "Iniciado Contato" | "Na mão" | "Retorno OC" | "Plágio" | "Retorno Plágio" | "Revisão" | "Retorno Revisão" | "Gramática" | "Retorno Gramática" | "Pronto para DTI" | "Pendente Interação" | "HTML Pronto" | "Revisão Final" | "Pronto" | "Problema",
    carga: string,
    orcamento: string,
    versao: string,
    recursosEspeciaisLicao: string,
    licaoAutorizada: string,
    catProblemaLicao: string,
    descProblemaLicao: string,
    dataPrevistaInicio: Date | "",
    dataEfetivaInicio: Date | "",
    dataPrevistaNaMao: Date | "",
    dataEfetivaNaMao: Date | "",
    dataPrevistaVT: Date | "",
    dataEfetivaVT: Date | "",
    dataPrevistaGramatica: Date | "",
    dataEfetivaGramatica: Date | "",
    videos: Video[],
    excluido: "" | "Excluído",
}